name: alicia
description: Alicia
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  concentric_transition: ^1.0.3
  dio: ^5.4.2+1
  either_dart: ^1.0.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  go_router: ^13.1.0
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  retrofit: ^4.1.0
  shimmer: ^3.0.0
  riverpod: ^2.5.0
  speech_to_text: ^6.6.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  freezed: ^2.5.0
  retrofit_generator: ^8.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 30

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/lotties/
    - assets/images/svg/
    - assets/images/png/
    - assets/lotties/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        